from django.core.exceptions import ValidationError


def validate_telephone(value):
    
    return value